packages:
  - name: packages
    actions:
      - name: getContacts
        runtime: 'nodejs:18'
        limits:
	  timeout: 5000
	  memory: 256
      - name: postContact
        runtime: 'nodejs:18'
        limits:
          timeout: 5000
          memory: 256
  